'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import { Provider } from 'react-redux';
import store from './redux/store'; // 路径可能根据你的项目结构有所不同


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  )
}
